# Erbt von deiner eigenen Basis
FROM git.zyata.de/zyata/zyata-workstation:44

# Spezifische Pakete für Office-Arbeiten
RUN dnf5 install -y google-inter-fonts libreoffice libreoffice-calc libreoffice-writer libreoffice-draw libreoffice-impress libreoffice-langpack-de libreoffice-opensymbol-fonts libreoffice-pdfimport libreoffice-filters && dnf5 clean all
