# Erbt von deiner eigenen Basis
FROM ghcr.io/pwfraley/lia-workstation:44

# Spezifische Pakete für Devloper-Arbeiten
RUN dnf5 install -y libvirt virt-manager distrobox \
    dotnet-sdk-10.0 just && \
    dnf5 clean all

RUN dnf5 group install -y development-tools && dnf5 clean all

RUN curl -fsSL https://pkg.claude-desktop-debian.dev/rpm/claude-desktop.repo -o /etc/yum.repos.d/claude-desktop.repo && \
    dnf5 install claude-desktop -y


RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | tee /etc/yum.repos.d/vscode.repo > /dev/null && \
    dnf5 check-update && \
    dnf5 -y install code && \
    dnf5 clean all

RUN dnf5 install -y fuse fuse-libs && \
    dnf5 clean all
